import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Poppins } from 'next/font/google'
import TanstackProvider from '@/components/providers/TansackProvider'


const roboto = Roboto ({
  subsets: ['latin'],
  variable: "--font-roboto",
  weight: ["100", "300","400", "500"]
})

const poppins = Poppins ({
  subsets: ['latin'],
  variable: "--font-poppins",
  weight: ["100", "300","400", "500"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="" >
      <TanstackProvider>
          <body className={`${poppins.variable}`} >
            <main>
              {children}    
            </main>
          </body>
      </TanstackProvider>
    </html>
  )
}
