import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'


const roboto = Roboto ({
  subsets: ['latin'],
  variable: "--font-roboto",
  weight: ["100", "300","400", "500"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable}`} >
      <body className="bg-bgColor" >{children}</body>
    </html>
  )
}
